name = "ClonalMarkov"
uuid = "850f068f-74c8-48a6-993f-91700854c8e3"
version = "1.0.0-DEV"
authors = ["Ryan Young <ryoung@brandeis.edu> and contributors"]

[deps]
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
JSON = "0.21.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
